<!-- ascent search -->

<div class="live_search">
<div id="searcharea">
<label for="search"><h2>Search</h2></label>
<input class="span12" type="search" name="search" id="search" placeholder="Enter your search terms..." />
<div id="update"></div>
</div> <!-- end search -->
</div>

<script src="js/jquery.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.ba-throttle-debounce.js"></script>
<script src="js/search.js"></script>